### PR TITLE
Added support for IPv6 default local address ::1

### PR DESCRIPTION
**Pull request by davereid**
To support faster Chrome lookups.

### CODE REVIEW

**Comment by 8draco8** [comment]
Please merge that pull request because on freshly installed OSX 10.10 (not updated from previous versions) IPv6 is enabled by default and entries with only IPv4 address in hosts are not working! I've spent 2 days looking for a solution to this problem and it would be nice to have this sorted out of the box.

**Comment by Cottser** [comment]
@8draco8 the pull request doesn't merge cleanly and I would like the host entries to be grouped if we go this route. Otherwise I have no objections to this, although I'm not sure why IPv4 wouldn't work – that seems troubling. Can you make a new issue/PR please? I would also love to see some resources to back up what you're saying, it sounds like you're saying the defaults are different for fresh install vs. upgrade.

**Comment by davereid** [comment]
I'll re-open a new PR

**Comment by davereid** [comment]
@Cottser Also, hah, I had no idea you maintained this. :)

**Comment by Cottser** [comment]
@davereid Thanks! I just started maintaining this last summer because I was using it a lot and @pgib agreed to move it to a GH organization and let me at it :)

**Comment by 8draco8** [comment]
According to my research OS X during update is keeping user settings like wallpapers, colours of bars etc. I didn't find any exact pointers to IPv6 setting but I assume it's just another setting that is leaved as user specific setting. That's why on new installations default is different than on update ones

**Pull request closed without merging**
